// Funkce pro vykreslení tabulky s otázkami a odpověďmi
function renderTable() {
  const table = document.getElementById('question-table');

  // Vyčistění obsahu tabulky
  while (table.rows.length > 1) {
      table.deleteRow(1);
  }

  const searchTerm = document.getElementById('search-bar').value.toLowerCase();

  // Filtrujeme otázky na základě hledaného výrazu
  const filteredData = data.filter(item =>
      item.otazka.toLowerCase().includes(searchTerm) ||
      item.odpoved.toLowerCase().includes(searchTerm)
  );

  // Vykreslení řádků tabulky pro každou odpovídající otázku a odpověď
  filteredData.forEach(item => {
      const row = table.insertRow();
      //const questionCell = row.insertCell(0);
      const answerCell = row.insertCell(0);

      //questionCell.innerHTML = item.otazka;
      answerCell.innerHTML = item.odpoved;
  });
}

// Při načtení stránky vykreslíme tabulku
window.onload = renderTable;

// Při změně hodnoty v hledacím poli vykreslíme tabulku znovu
document.getElementById('search-bar').addEventListener('input', renderTable);

const data = [
  { otazka: 'Default', odpoved: 'There are no visible elements to preview for this webpage. ' }, //zde nejsou žádne prvky anglicky 
  { otazka: 'In which situation would an ESD strike potentially cause harm to the PC?', odpoved: 'when replacing a mechanical hard drive with an M.2 SSD' },
  { otazka: 'A person has started a new technical job. In which situation would ESD be an issue?', odpoved: 'when installing a processor' },
  { otazka: 'A technician is about to begin preventive maintenance on a company PC. In which situation would ESD be an issue?', odpoved: 'when replacing a motherboard' },
  { otazka: 'A technician is about to begin preventive maintenance on a company PC. In which situation would ESD be an issue?', odpoved: 'when installing RAM' },
  { otazka: 'In which situation would an ESD strike potentially cause harm to the PC?', odpoved: 'when replacing a mechanical hard drive with an M.2 SSD' },
  { otazka: 'An instructor has given a student an assignment to assemble a PC. In which situation should the student be aware that ESD is an issue?', odpoved: 'when installing RAM' },
  { otazka: 'A technician is about to begin preventive maintenance on a company PC. In which situation would ESD be an issue?', odpoved: 'when replacing a motherboard' },
  { otazka: 'A person has started a new technical job. In which situation would ESD be an issue?', odpoved: 'when installing a processor' },
  { otazka: 'A technician is about to begin preventive maintenance on a company PC. In which situation would ESD be an issue?', odpoved: 'when replacing a motherboard' },
  { otazka: 'In which situation would an ESD strike potentially cause harm to the PC?', odpoved: 'when replacing a mechanical hard drive with an M.2 SSD' },
  { otazka: 'What two motherboard components control the system boot operations?', odpoved: 'BIOS chip-UEFI chip' },
  { otazka: 'A technician is upgrading an ATX motherboard with another ATX motherboard. Which component might be affected by this and need to be upgraded and bought as an additional purchase?', odpoved: 'CPU' },
  { otazka: 'A customer has requested that a PC be built that will support eSATA. Which component should be checked to be sure that this feature is supported?', odpoved: 'chipset' },
  { otazka: 'Which memory module used to hold instructions for booting a PC and loading the OS but is still used on adapters even though the memory contents cannot be changed?', odpoved: 'ROM' },
  { otazka: 'What is a characteristic of DDR SDRAM?', odpoved: 'It transfers data twice per clock cycle compared to once per clock cycle for SDRAM.' },
  { otazka: 'What are two safety hazards when dealing with laser printers?', odpoved: 'high voltage - hot components' },
  { otazka: 'Which component requires a technician to install screws externally through the PC case?', odpoved: 'power supply' },
  { otazka: 'A technician is installing an internal HDD. To which motherboard connector will the technician connect the data cable?', odpoved: 'SATA' },
  { otazka: 'Refer to the exhibit. A technician has been asked to install a video card. Which section of the motherboard will the technician use to install the card?', odpoved: 'section D' },
  { otazka: 'When a PC is being assembled what component is connected to the motherboard with a SATA cable?', odpoved: 'the optical drive' },
  { otazka: 'A technician is troubleshooting a computer that is experiencing hardware failure detected by the BIOS. What is one way this failure is indicated?', odpoved: 'The computer emits a pattern of beeps indicating the failing device.' },
  { otazka: 'Which three features can be configured in the BIOS settings to secure a computer?', odpoved: 'drive encryption-TPM-passwords' },
  { otazka: 'What is the purpose of RAID adapters?', odpoved: 'to connect multiple storage devices for redundancy or speed' },
  { otazka: 'When a new motherboard is being installed between which two components must thermal compound be applied?', odpoved: 'CPU-heat sink' },
  { otazka: 'What is the purpose of a Safety Data Sheet?', odpoved: 'to specify procedures for dealing with potentially hazardous materials' },
  { otazka: 'Which negative environmental factor does cleaning the inside of a computer reduce?', odpoved: 'dust' },
  { otazka: 'What is a recommended procedure to follow when cleaning computer components?', odpoved: 'Hold cans of compressed air upright while spraying' },
  { otazka: 'On the production floor a furniture plant has laptops for process monitoring and reporting. The production floor environment is around 80 degrees Fahrenheit (27 degrees Celsius). The humidity level is fairly high around 70 percent. Fans are mounted in the ceiling for air circulation. Wood dust is prevalent. Which condition is most likely to adversely affect a laptop that is used in this environment?', odpoved: 'the dust' },
  { otazka: 'After a technician tests a theory of probable causes what two actions should the technician take if the testing did not identify an exact cause?', odpoved: 'Establish a new theory of probable causes-Document each test tried that did not correct the problem' },
  { otazka: 'What would happen if a PC that contains a power supply that does not automatically adjust for input voltage is set to 230 volts and attaches to an outlet in the United States?', odpoved: 'The PC would not turn on.' },
  { otazka: 'Which type of network spans a single building or campus and provides services and applications to people within a common organizational structure?', odpoved: 'LAN' },
  { otazka: 'What are two types of wired high-speed Internet connections?', odpoved: 'cable-DSL' },
  { otazka: 'In what two situations would UDP be better than TCP as the preferred transport protocol?', odpoved: 'when a faster delivery mechanism is needed-when applications do not need to guarantee delivery of the data' },
  { otazka: 'The current IP configuration of a small company is done manually and is time-consuming. Because of increased network growth a technician needs a simpler way for IP configuration of workstations. Which service would simplify the workstation IP configuration task?', odpoved: 'DHCP' },
  { otazka: 'A company is looking for a next-generation firewall that provides VPN functionality IDS/IPS functionality and DoS/DDoS protection. Which device would be best suited for this task?', odpoved: 'UTM' },
  { otazka: 'A student is helping a friend with a home computer that can no longer access the Internet. Upon investigation the student discovers that the computer has been assigned the IP address 169.254.100.88. What could cause a computer to get such an IP address?', odpoved: 'unreachable DHCP server' },
  { otazka: 'What three values must be added to the IPv4 properties of a NIC in order for a computer to have basic connectivity with the network?', odpoved: 'subnet mask-default gateway-IP address' },
  { otazka: 'A device has an IPv6 address of 2001:0DB8:75a3:0214:0607:1234:aa10:ba01 /64. What is the host identifier of the device?', odpoved: '0607:1234:aa10:ba01' },
  { otazka: 'How can a user prevent specific applications from accessing a Windows computer over a network?', odpoved: 'Block specific TCP or UDP ports in Windows Firewall.' },
  { otazka: 'Place the six stages of the troubleshooting process in the correct order', odpoved: 'Search Step1-Step2-Step3-Step4-Step5-Step6' },
  { otazka: 'A technician has been asked to configure Wi-Fi calling on a corporate mobile device. In which situation would this feature be most advantageous?', odpoved: 'when in an area with poor cellular coverage' },
  { otazka: 'Which statement is true about laptops?', odpoved: 'Most of the internal components that are designed for laptops cannot be used for desktops.' },
  { otazka: 'Which standard provides a bridge between laptop hardware and the operating system and a way for technicians to configure power management schemes to get the best performance?', odpoved: 'ACPI' },
  { otazka: 'Which two laptop components are considered replaceable by the customer', odpoved: 'battery-RAM' },
  { otazka: 'A user wants to synchronize some apps movies music and ebooks between mobile devices. What are the two types of connections used to synchronize this type of data?', odpoved: 'WiFi-USB' },
  { otazka: 'A technician is explaining the differences between inkjet printers and laser printers to a customer. Which two comparisons should the technician make?', odpoved: 'Inkjet printers are less expensive as an initial purchase than laser printers.-The laser printer output is dry after printing but an inkjet printer may still have wet ink on the paper after printing.' },
  { otazka: 'A user chooses the collate option and prints two copies of a three-page document. What is the order in which the pages are printed?', odpoved: 'pages 1-2-3-1-2-3' },
  { otazka: 'A color laser printer is used to print documents with graphics and photographs. Users are complaining that printing takes too long. Which component of the printer should be upgraded in order to improve printing performance?', odpoved: 'RAM' },
  { otazka: 'What service is available for Windows to provide software print server services to MAC OS clients?', odpoved: 'Bonjour Print Server' },
  { otazka: 'Which three components are typically found in laser printer maintenance kits?', odpoved: 'fuser assembly-pickup rollers-transfer rollers' },
  { otazka: 'A technician is installing a new printer in a cool damp environment. After the printer cabling is done and the software and print driver are installed the printer test page jams. What is the most likely cause of the print failure?', odpoved: 'too much humidity' },
  { otazka: 'A data center has recently updated a physical server to host multiple operating systems on a single CPU. The data center can now provide each customer with a separate web server without having to allocate an actual discrete server for each customer. What is the networking trend that is being implemented by the data center in this situation?', odpoved: 'virtualization' },
  { otazka: 'How does virtualization help with disaster recovery within a data center?', odpoved: 'Hardware does not have to be identical.' },
  { otazka: 'Which two hypervisors are suitable to support virtual machines in a data center?', odpoved: 'VMware ESX/ESXi-Microsoft Hyper-V 2012' },
  { otazka: 'A web designer accesses a company Windows 10 computer remotely. The designer often needs to simultaneously open multiple applications such as a web page editor and a graphics editor. Rather than opening them in multiple windows the designer opens them in different virtual desktops. What technology is being used by the designer?', odpoved: 'Windows Virtual Desktop' },
  { otazka: 'Which Cloud computing service would be best for an organization that needs to collaboratively create applications and deliver them over the web?', odpoved: 'PaaS' },
  { otazka: 'Which statement describes a feature of SDRAM?', odpoved: 'It can process overlapping instructions in parallel.' },
  { otazka: 'Match the memory type to the feature.', odpoved: 'Search: Its connector has' },
  { otazka: 'A technician is troubleshooting a server that displays the error message RAID not found after a power outage over the weekend. What is a possible cause for this?', odpoved: 'The external RAID controller is not receiving power.' },
  { otazka: 'A customer brings in a laptop with a touch screen that is not working correctly. The touch screen either does not respond at all or provides unusual or inaccurate responses. What is a possible cause for such behavior?', odpoved: 'Too many apps are open.' },
  { otazka: 'What are two security risks associated with sharing printers in a corporate environment?', odpoved: 'user authentication-cached files' },
  { otazka: 'Which change management process component is concerned with the business processes that are affected by changes?', odpoved: 'assessment' },
  { otazka: 'Match the problem to the possible solution.', odpoved: 'Search: MTP' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses mirroring and striping which RAID level is the technician using?', odpoved: '10' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses mirroring which RAID level is the technician using?', odpoved: '1' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses striping with parity which RAID level is the technician using?', odpoved: '5' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses striping which RAID level is the technician using?', odpoved: '0' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses striping with double parity which RAID level is the technician using?', odpoved: '6' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses striping with double parity which RAID level is the technician using?', odpoved: '6' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses mirroring which RAID level is the technician using?', odpoved: '1' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses mirroring and striping which RAID level is the technician using?', odpoved: '10' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses striping with parity which RAID level is the technician using?', odpoved: '5' },
  { otazka: 'A computer technician is installing a RAID. If the RAID uses striping which RAID level is the technician using?', odpoved: '0' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of an old battery?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of a broken monitor?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of an old power supply?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of old RAM?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of old RAM?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of an old motherboard?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of an old hard drive?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of an old hard drive?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of an old battery?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'A technician is upgrading many PCs used within the company. How should the technician dispose of an old battery?', odpoved: 'Recycle following local regulations.' },
  { otazka: 'After continuous morning use a computer suddenly reboots without the intervention of the user. What are the two most likely hardware parts that could cause this problem?', odpoved: 'CPU-power supply' },
  { otazka: 'After continuous morning use a computer suddenly reboots without the intervention of the user. What are the two most likely hardware parts that could cause this problem?', odpoved: 'CPU-power supply' },
  { otazka: 'After continuous morning use a computer suddenly reboots without the intervention of the user. What are the two most likely hardware parts that could cause this problem?', odpoved: 'CPU-power supply' },
  { otazka: 'A technician has been called in to investigate a problem with the computer rebooting randomly throughout the day. What two pieces of hardware could cause this problem?', odpoved: 'power supply-CPU' },
  { otazka: 'A technician has been called in to investigate a problem with the computer rebooting randomly throughout the day. What two pieces of hardware could cause this problem?', odpoved: 'power supply-CPU' },
  { otazka: 'For two days in a row a user has noticed that the computer reboots several times before it eventually starts. What are two suspect components?', odpoved: 'power supply-CPU' },
  { otazka: 'For two days in a row a user has noticed that the computer reboots several times before it eventually starts. What are two suspect components?', odpoved: 'power supply-CPU' },
  { otazka: 'While a user is working on a spreadsheet the computer reboots. What are two components that could cause this issue?', odpoved: 'power supply-CPU' },
  { otazka: 'While a user is working on a spreadsheet the computer reboots. What are two components that could cause this issue?', odpoved: 'power supply-CPU' },
  { otazka: 'After continuous morning use a computer suddenly reboots without the intervention of the user. What are the two most likely hardware parts that could cause this problem?', odpoved: 'CPU-power supply' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 137. What service application is the client requesting?', odpoved: 'NetBIOS (NetBT)' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 22. What service application is the client requesting?', odpoved: 'SSH' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 143. What service application is the client requesting?', odpoved: 'IMAP' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 23. What service application is the client requesting?', odpoved: 'Telnet' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 161. What service application is the client requesting?', odpoved: 'SNMP' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 389. What service application is the client requesting?', odpoved: 'LDAP' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 25. What service application is the client requesting?', odpoved: 'SMTP' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 427. What service application is the client requesting?', odpoved: 'SLP' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 53. What service application is the client requesting?', odpoved: 'DNS' },
  { otazka: 'A client packet is received by a server. The packet has a destination port number of 427. What service application is the client requesting?', odpoved: 'SLP' },
  { otazka: 'Which is the compressed format of the IPv6 address 2001:0db8:0000:0000:0000:a0b0:0008:0001?', odpoved: '2001:db8::a0b0:8:1' },
  { otazka: 'Which is the compressed format of the IPv6 address fe80:09ea:0000:2200:0000:0000:0fe0:0290?', odpoved: 'fe80:9ea:0:2200::fe0:290' },
  { otazka: 'Which is the compressed format of the IPv6 address 2002:0042:0010:c400:0000:0000:0000:0909?', odpoved: '2002:42:10:c400::909' },
  { otazka: 'Which is the compressed format of the IPv6 address fe80:09ea:0000:2200:0000:0000:0fe0:0290?', odpoved: 'fe80:9ea:0:2200::fe0:290' },
  { otazka: 'Which is the compressed format of the IPv6 address 2002:0420:00c4:1008:0025:0190:0000:0990?', odpoved: '2002:420:c4:1008:25:190::990' },
  { otazka: 'Which is the compressed format of the IPv6 address 2001:0db8:0000:0000:0ab8:0001:0000:1000?', odpoved: '2001:db8::ab8:1:0:1000' },
  { otazka: 'Which is the compressed format of the IPv6 address fe80:0000:0000:0000:0220:0b3f:f0e0:0029?', odpoved: 'fe80::220:b3f:f0e0:29' },
  { otazka: 'Which is the compressed format of the IPv6 address 2001:0db8:0000:0000:0000:a0b0:0008:0001?', odpoved: '2001:db8::a0b0:8:1' },
  { otazka: 'Which is the compressed format of the IPv6 address fe80:09ea:0000:2200:0000:0000:0fe0:0290?', odpoved: 'fe80:9ea:0:2200::fe0:290' },
  { otazka: 'Which is the compressed format of the IPv6 address fe80:9ea0:0000:2020:0000:00bf:00e0:9290?', odpoved: 'fe80:9ea0::2020:0:bf:e0:9290' },
  { otazka: 'What ACPI power state describes when the CPU and RAM are off and the contents of RAM have been saved to a temporary file on the hard drive?', odpoved: 'S4' },
  { otazka: 'What ACPI power state describes when the CPU and RAM are still receiving power but unused devices are powered down?', odpoved: 'S1' },
  { otazka: 'What ACPI power state describes when the CPU is off but the RAM is refreshed?', odpoved: 'S2' },
  { otazka: 'What ACPI power state describes when the computer is off?', odpoved: 'S5' },
  { otazka: 'What ACPI power state describes when the computer is off?', odpoved: '' },
  { otazka: 'What ACPI power state describes when the CPU is off and the RAM is set to a slow refresh rate often called suspend mode?', odpoved: 'S3' },
  { otazka: 'What ACPI power state describes when the computer is on and the CPU is running?', odpoved: 'S0' },
  { otazka: 'What ACPI power state describes when the CPU and RAM are still receiving power but unused devices are powered down?', odpoved: 'S1' },
  { otazka: 'What ACPI power state describes when the CPU and RAM are off and the contents of RAM have been saved to a temporary file on the hard drive?', odpoved: 'S4' },
  { otazka: 'What ACPI power state describes when the computer is off?', odpoved: 'S5' },
  { otazka: 'A reporter is trying to print several high resolution photographs but the color laser printer is going extremely slowly. What should the technician do to resolve the issue?', odpoved: 'Add more RAM to the printer.' },
  { otazka: 'A new printer has just been installed deep in a mine. When test pages are printed the paper constantly jams. What should the technician do to resolve the issue?', odpoved: 'Move the printer to a less-humid location.' },
  { otazka: 'A user complains that recently every printed document has vertical lines and streaks on the paper. What should the technician do to resolve the issue?', odpoved: 'Distribute the toner more evenly within the cartridge.' },
  { otazka: 'A user complains that recently every printed document has vertical lines and streaks on the paper. What should the technician do to resolve the issue?', odpoved: 'Distribute the toner more evenly within the cartridge.' },
  { otazka: 'A school is installing a new shared printer but the printer is not showing up on the list of available printers. What should the technician do to resolve the issue?', odpoved: 'Manually add the printer IP address.' },
  { otazka: 'A school is installing a new shared printer but the printer is not showing up on the list of available printers. What should the technician do to resolve the issue?', odpoved: 'Manually add the printer IP address.' },
  { otazka: 'Employees are complaining that they send print jobs to a newly installed printer but the print jobs never print. What should the technician do to resolve the issue?', odpoved: 'The printer is connected to the wrong port. Modify the port.' },
  { otazka: 'Users have noticed that the colors on their printed documents are different from the colors that they see on their computer screens. What should the technician do to resolve the issue?', odpoved: 'Calibrate the printer.' },
  { otazka: 'A technician has just completed a preventive maintenance on the department printer. Users are now complaining that the printer is no longer available. What should the technician do to resolve the issue?', odpoved: 'Check that the printer is plugged into a power source.' },
  { otazka: 'Employees of a small business are complaining that the printer is printing faded images. What should the technician do to resolve the issue?', odpoved: 'Replace the toner cartridge.' },
  { otazka: 'A photographer is complaining about the following printer issue: The printer issues a Document failed to print message. What are two possible causes of this issue? (Choose two.)', odpoved: 'A cable is loose or disconnected.-The printer is no longer shared.' },
  { otazka: 'A reporter is complaining about the following printer issue: The printer is printing unknown characters. What are two possible causes of this issue? (Choose two.)', odpoved: 'The wrong or an outdated printer driver is installed.-The printer has a loose connection.' },
  { otazka: 'A manager is complaining about the following printer issue: The printer is printing incorrect colors. What are two possible causes of this issue? (Choose two.)', odpoved: 'The print heads might need to be cleaned and calibrated.-An incorrect cartridge could be installed.' },
  { otazka: 'A librarian is complaining about the following printer issue: The printer control panel displays no image. What are two possible causes of this issue? (Choose two.)', odpoved: 'The toner cartridge is low.-The paper might be incompatible with the printer.' },
  { otazka: 'A teacher is complaining about the following printer issue: The paper is creased after printing. What are two possible causes of this issue? (Choose two.)', odpoved: 'The paper-feed tray might not be firmly adjusted against the edges of the printer.-The paper might be loaded incorrectly.' },
  { otazka: 'A receptionist is complaining about the following printer issue: My impact printer produces faded or light characters. What are two possible causes of this issue? (Choose two.)', odpoved: 'The ribbon may be worn out.-The ribbon may be damaged.' },
  { otazka: 'A photographer is complaining about the following printer issue: The paper is not being fed into the printer. What are two possible causes of this issue? (Choose two.)', odpoved: 'The paper may be wrinkled.-The printer could be set to print to a different paper size than is currently loaded.' },
  { otazka: 'A reporter is complaining about the following printer issue: The printer is printing unknown characters. What are two possible causes of this issue? (Choose two.)', odpoved: 'The wrong or an outdated printer driver is installed.-The printer has a loose connection.' },
  { otazka: 'A manager is complaining about the following printer issue: The printer is printing incorrect colors. What are two possible causes of this issue? (Choose two.)', odpoved: 'The print heads might need to be cleaned and calibrated.-An incorrect cartridge could be installed.' },
  { otazka: 'A laptop has an NVMe drive (C:) and a mechanical hard drive (D:). When the user tries to save a spreadsheet to the D: drive the user notices that the D: drive is not there. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use the Disk Management Control Panel.' },
  { otazka: 'A computer has two mechanical hard drives. The second drive (D:) is used for data storage. When trying to save an email attachment to the local hard drive the user notices that the D: drive is not an option. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use File Explorer.' },
  { otazka: 'A user reports that a drive is no longer there. The technician asks the user to demonstrate the problem. Within the application the user demonstrates that the drive that was present in the save options yesterday is now no longer an option. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use Device Manager.' },
  { otazka: 'A computer has two mechanical hard drives. The second drive (D:) is used for data storage. When trying to save an email attachment to the local hard drive the user notices that the D: drive is not an option. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use File Explorer.' },
  { otazka: 'A computer has an SSD for the operating system and applications and uses another mechanical hard drive for data storage. The user reports that data can no longer be saved to the mechanical hard drive. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use File Explorer.' },
  { otazka: 'A user reports that a drive is no longer there. The technician asks the user to demonstrate the problem. Within the application the user demonstrates that the drive that was present in the save options yesterday is now no longer an option. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use Device Manager.' },
  { otazka: 'A laptop has an NVMe drive (C:) and a mechanical hard drive (D:). When the user tries to save a spreadsheet to the D: drive the user notices that the D: drive is not there. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use the Disk Management Control Panel.' },
  { otazka: 'A computer has an SSD for the operating system and applications and uses another mechanical hard drive for data storage. The user reports that data can no longer be saved to the mechanical hard drive. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use Device Manager.' },
  { otazka: 'A laptop has an NVMe drive (C:) and a mechanical hard drive (D:). When the user tries to save a spreadsheet to the D: drive the user notices that the D: drive is not there. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use the Disk Management Control Panel.' },
  { otazka: 'A computer has an SSD for the operating system and applications and uses another mechanical hard drive for data storage. The user reports that data can no longer be saved to the mechanical hard drive. What should the technician do to see if the drive is recognized by the operating system?', odpoved: 'Use File Explorer.' },
  { otazka: 'A technician is working on a laptop and the GPS is not functioning. What is a probable cause for this situation?', odpoved: 'A service is disabled.' },
  { otazka: 'A technician is working on a laptop and the GPS is not functioning. What is a probable cause for this situation?', odpoved: 'Airplane mode is turned on.' },
  { otazka: 'A technician is working on a laptop and the GPS is not functioning. What is a probable cause for this situation?', odpoved: 'Airplane mode is turned on.' },
  { otazka: 'A technician is working on a laptop and the GPS is not functioning. What is a probable cause for this situation?', odpoved: 'Airplane mode is turned on.' },
  { otazka: 'A technician is working on a laptop and an app is not loading. What is a probable cause for this situation?', odpoved: 'An app needs to be restarted.' },
  { otazka: 'A technician is working on a laptop and an app is not loading. What is a probable cause for this situation?', odpoved: 'An app needs to be restarted.' },
  { otazka: 'A technician is working on a laptop and an app is not responding. What is a probable cause for this situation?', odpoved: 'An app needs to be restarted.' },
  { otazka: 'A technician is working on a laptop and an app is not responding. What is a probable cause for this situation?', odpoved: 'An app needs to be restarted.' },
  { otazka: 'A technician is working on a laptop and an error message about decryption appears when opening an email. What is a probable cause for this situation?', odpoved: 'A digital certificate is missing.' },
  { otazka: 'A technician is working on a laptop and an error message about decryption appears when opening an email. What is a probable cause for this situation?', odpoved: 'A digital certificate is missing.' },
  { otazka: 'Students who use the same printer are complaining that recently printed documents contain unknown characters. What should the technician do to resolve the issue?', odpoved: 'Re-install the printer driver.' },
  { otazka: 'Students who use the same printer are complaining that recently printed documents contain unknown characters. What should the technician do to resolve the issue?', odpoved: 'Re-install the printer driver.' },
  { otazka: 'An office assistant in a law firm is trying to print many large legal documents but is getting memory overload error messages from the printer. What should the technician do to resolve the issue?', odpoved: 'Add more memory to the printer.' },
  { otazka: 'An office assistant in a law firm is trying to print many large legal documents but is getting memory overload error messages from the printer. What should the technician do to resolve the issue?', odpoved: 'Add more memory to the printer.' },
  { otazka: 'A user is complaining that the printer is printing pages with no image on them. What should the technician do to resolve the issue?', odpoved: 'Replace the toner cartridge.' },
  { otazka: 'Students who use the same printer are complaining that recently printed documents contain unknown characters. What should the technician do to resolve the issue?', odpoved: 'Re-install the printer driver.' },
  { otazka: 'Students who use the same printer are complaining that recently printed documents contain unknown characters. What should the technician do to resolve the issue?', odpoved: 'Re-install the printer driver.' },
  { otazka: 'Users have noticed that the colors on their printed documents are different from the colors that they see on their computer screens. What should the technician do to resolve the issue?', odpoved: 'Calibrate the printer.' },
  { otazka: 'Step1:', odpoved: 'Identify the problem.' },
  { otazka: 'Step2:', odpoved: 'Establish a theory of probable cause.' },
  { otazka: 'Step3:', odpoved: 'Test the theory to determine the cause.' },
  { otazka: 'Step4:', odpoved: 'Establish a plan of action to resolve the problem and implement the solution.' },
  { otazka: 'Step5:', odpoved: 'Verify full system functionallity and if applicable implement preventive measures.' },
  { otazka: 'Step6:', odpoved: 'Document findings actions and outcomes.' },
  { otazka: 'Its connector has 184 pins and is able to support two writes and two reads per CPU clock cycle:', odpoved: 'DDR SDRAM' },
  { otazka: 'Its connector has 240 pins and consumes 1.8 Volts of power:', odpoved: 'DDR2 SDRAM' },
  { otazka: 'Its connector has 240 pins and consumes 1.5 Volts of power:', odpoved: 'DDR3 SDRAM' },
  { otazka: 'Its connector has 288 pins and has advanced error correction features available:', odpoved: 'DDR4 SDRAM' },
  { otazka: 'MTP Replace the motherboard:', odpoved: 'The motherboard capacitors are distended swollen emitting residue or bulging.' },
  { otazka: 'MTP Check fo faulting cable damaged or mis-seated CPU or other motherbard component prior to replacing the motherboard if required:', odpoved: 'The user can hear the fans spinning but the PC will not start and there are no beeps from the speaker.' },
  { otazka: 'MTP Update the BIOS firmware:', odpoved: 'After upgrading the single core CPU to a dual core CPU only one CPU graph is seen in the task manager.' },
  { otazka: 'MTP Connect the auxillary power cable for the adapter card:', odpoved: 'The computer does not display any video after installing a new PCIe video card.' },


  { otazka: 'Which two tools are available to transfer user data and settings from an old Windows computer to a Windows operating system on a new computer?', odpoved: 'Windows Easy Transfer-User State Migration tool' },
  { otazka: 'A user wants to extend a primary partition formatted with the NTFS file system with the unallocated space on the hard disk. What must the user do after the primary partition is extended to make it usable?', odpoved: 'Convert the disk type to dynamic.' },
  { otazka: 'Why is a full format more beneficial than a quick format when preparing for a clean OS installation?', odpoved: 'A full format will delete files from the disk while analyzing the disk drive for errors.' },
  { otazka: 'Match the Windows 10 boot sequence after the boot manager (bootmgr.exe) loads.', odpoved: ' Search:StepOne-StepTwo-StepThree-StepFour-StepFive' },
  { otazka: 'Match the correct API with its function within the Windows 10 environment.', odpoved: 'Search:MTC This' },
  { otazka: 'A technician wishes to prepare the computers in the network for disaster recovery. The network consists of a variety of desktops and laptops from different vendors. All the computers are running either a 32-bit version of Windows 10 Pro or a 64-bit version of Windows 10 Pro. How would the technician prepare the recovery media?', odpoved: 'Prepare individual recovery discs for all the computers.' },
  { otazka: 'A technician wishes to deploy Windows 10 Pro to multiple PCs through the remote network installation process. The technician begins by connecting the new PCs to the network and booting them up. However the deployment fails because the target PCs are unable to communicate with the deployment server. What is the possible cause?', odpoved: 'The NIC cards on the new PCs are not PXE-enabled.' },
  { otazka: 'Which condition is required when planning to install Windows on a GPT disk?', odpoved: 'The computer must be UEFI-based.' },
  { otazka: 'A technician wishes to perform a customized unattended network installation of Windows 10 on a PC. The requirements include the installation of specific applications and device drivers through the use of an answer file. What would the technician use to create the answer file?', odpoved: 'Windows SIM' },
  { otazka: 'An organization has purchased a custom application for the sales staff that can only be installed on a 64-bit Windows operating system. Each member of the sales staff has a Windows 8.1 32-bit PC. What must the IT department do in order to install and run the application on the sales staff computers?', odpoved: 'Perform a clean installation of 64-bit Windows 10.' },
  { otazka: 'Match the tabs of the Windows 10 Task Manager to their functions. (Not all options are used.)', odpoved: ' Search:MTT' },
  { otazka: 'Match the drive status indicators in the Disk Management utility with their description. (Not all options are used.)', odpoved: 'Search:MTD' },
  { otazka: 'Match the wireless security settings to the description. (Not all options are used.)', odpoved: 'Search:MTW' },
  { otazka: 'What are two possible solutions to any Windows computer restarting continuously and never displaying the desktop? (Choose two.)', odpoved: 'Press F8 to open the Advanced Options menu and choose Disable Automatic Restart on System Failure.-Run chkdsk /F /R from the recovery console.' },
  { otazka: 'A technician uses Microsoft Deployment Image Servicing and Management (DISM) tool to create a Windows image file on one of the workstations running Windows 10. When the technician tries to clone another workstation with the image file the workstation exhibits network connectivity issues on completion. What could cause this?', odpoved: 'The SID of the original PC is not cleared when creating the image with DISM.' },
  { otazka: 'A user complains that user files cannot be synced with the network file server while the user is traveling out of the office. The user had access to the internet but no access to the company network server. How can this be addressed?', odpoved: 'Setup a Sync partnership between the network server Microsoft OneDrive and the user.' },
  { otazka: 'A technician has connected a new internal hard drive to a Windows 10 PC. What must be done in order for Windows 10 to use the new hard drive?', odpoved: 'Initialize the new hard drive.' },
  { otazka: 'What service does PRINT$ provide?', odpoved: 'It provides printer drivers for printer administrators.' },
  { otazka: 'A technician is troubleshooting a Windows 10 laptop infected with a virus that has damaged the master boot record. The technician has booted the laptop using the installation media and is attempting to repair the laptop from the command line interface. Which command can the technician use to repair the corrupt master boot record?', odpoved: 'bootrec /fixmbr' },
  { otazka: 'A user reports that a Windows 10 PC displays the error message Invalid Boot Disk during the boot process. The IT technician attempts to boot the computer and finds that the error message occurs immediately after the POST. What could be the possible cause?', odpoved: 'The MBR/GPT is corrupted.' },
  { otazka: 'Which port number is used by Virtual Network Computing (VNC) to provide remote screen sharing between devices?', odpoved: '5900' },
  { otazka: 'Which feature is included with macOS and provides the ability for a remote user to view and change files folders and applications on the local computer?', odpoved: 'Screen Sharing' },
  { otazka: 'Which area of concern falls under the operations and planning category in IT documentation?', odpoved: 'inventory management' },
  { otazka: 'Match the individual languages with their corresponding classification.', odpoved: ' Search:MTI' },
  { otazka: 'Which two actions should a technician take if illegal content such as child pornography is discovered on the hard drive of a customer computer? (Choose two.)', odpoved: 'Contact a first responder.-Document as much information as possible.' },
  { otazka: 'What are three pieces of information a level one technician should gather from a customer? (Choose three.)', odpoved: 'contact information-description of the problem-details of any recent changes to the computer' },
  { otazka: 'details of any recent changes to the computer', odpoved: 'Let a customer finish talking before asking additional questions.-If you have to put the customer on hold ask the customer for permission.' },
  { otazka: 'A support desk technician is dealing with an angry customer. Which two approaches should the technician take in dealing with the customer? (Choose two.)', odpoved: 'Work to redirect the conversation to solving the problem.-Let the customer explain the problem without interrupting.' },
  { otazka: 'What two kinds of problems should be escalated from a level one technician to a level two technician? (Choose two.)', odpoved: 'problems that are complicated and will take a long time to resolve-problems that are beyond the scope of the knowledge of the level one technician' },
  { otazka: 'An IT technician in a service company has provided extensive remote IT support with product deployment for a customer. After the completion of the contract a complaint is filed against the IT technician for not following company policy by sending unsolicited emails about services and products that are not related to the contract. What two things should the IT support technician have done differently? (Choose two.)', odpoved: 'The IT technician should have researched the company policy about personal communication with customers on company time.-The IT technician should have asked the customer if the customer was interested in receiving information regarding other new services and products.' },
  { otazka: 'A third-party security firm is performing a security audit of a company and recommends the company utilize the Remote Desktop Protocol. What are two characteristics of the Microsoft Remote Desktop Protocol (RDP)? (Choose two.)', odpoved: 'RDP uses an encrypted session.-RDP connects on TCP port 3389.' },
  { otazka: 'Which subject area describes collecting and analyzing data from computer systems networks and storage devices as part of an investigation of alleged illegal activity?', odpoved: 'computer forensics' },
  { otazka: 'In a computer forensics investigation which type of data is considered volatile data and can be lost if power is removed from the computer?', odpoved: 'data in transit between RAM and the CPU' },
  { otazka: 'Refer to the exhibit. During the troubleshooting of software that is installed on a computer system a level one technician requires help from a level two technician. The file shown in the exhibit must be sent to the level two technician. How should the level one technician deliver this file?', odpoved: 'Replace all passwords in the file with <password omitted> before emailing the file and then supply the passwords by secure means if required.' },
  { otazka: 'What skill is essential for a level one technician to have?', odpoved: 'the ability to translate a description of a customer problem into a few succinct sentences and enter it into the work order' },
  { otazka: 'What is used to control illegal use of software and content?', odpoved: 'digital rights management' },
  { otazka: 'What determines the level of support that a call center technician will provide to an individual customer?', odpoved: 'Support is based on the SLA for that customer.' },
  { otazka: 'A bench technician enters the server room and finds the backup server computer case open. The hard drives containing patient medical data are all physically disconnected from the motherboard and the SATA data cables are hanging outside the case. Which step should the technician immediately take?', odpoved: 'Locate an employee qualified to collect evidence.' },
  { otazka: 'What is the difference between a scripting language and a compiled language?', odpoved: 'Scripting languages are interpreted and executed line by line when a script is run while compiled languages need to be converted into executable code.' },
  { otazka: 'Which methods can be used to implement multifactor authentication?', odpoved: 'passwords and fingerprints' },
  { otazka: 'When responding to a call from a customer who is experiencing problems with a computer the technician notices that a number of system files on the computer have been renamed. Which two possible solutions could the technician implement to resolve the problem? (Choose two.)', odpoved: 'Use antivirus software to remove a virus.-Restore the computer from a backup.' },
  { otazka: 'A technician suspects that a security issue is causing problems with a computer. What two actions could be performed to test theories of probable cause when troubleshooting the PC? (Choose two.)', odpoved: 'Log in as a different user.-Disconnect the computer from the network.' },
  { otazka: 'The CIO wants to secure data on company laptops by implementing file encryption. The technician determines the best method is to encrypt each hard drive using Windows BitLocker. Which two things are needed to implement this solution? (Choose two.)', odpoved: 'at least two volumes-TPM' },
  { otazka: 'What is an accurate description of asymmetric encryption technology?', odpoved: 'It is an encryption process that uses a public and private key pair to encrypt/decrypt data.' },
  { otazka: 'Which type of security threat can be transferred through email and is used to gain sensitive information by recording the keystrokes of the email recipient?', odpoved: 'virus' },
  { otazka: 'A manager reports that unusual things are happening on a Windows computer. The technician determines that malware is the culprit. What can the technician do to remove stubborn malware?', odpoved: 'Enter Safe Mode and do a system restore.' },
  { otazka: 'An employee that has worked at the company for many years has started a home-based business selling crafts. While leaving an office meeting a company supervisor notices the employee buying supplies for the personal crafting business of the employee. What section of the security policy should the supervisor review when determining how to handle this situation?', odpoved: 'acceptable use policies' },
  { otazka: 'What Windows utility should be used to configure password rules and account lockout policies on a system that is not part of a domain?', odpoved: 'Local Security Policy tool' },
  { otazka: 'A customer brings in a computer that is asking for a password as soon as it powers on even before the operating system boots. Which type of password is enabled?', odpoved: 'BIOS' },
  { otazka: 'When attempting to improve system performance for Linux computers with a limited amount of memory why is increasing the size of the swap file system not considered the best solution?', odpoved: 'A swap file system uses hard disk space to store inactive RAM content' },
  { otazka: 'What are three features of GPS on mobile devices? (Choose three.)', odpoved: 'navigation-specialized search results-device tracking' },
  { otazka: 'Which three components are used to assign file and directory permissions in Linux systems? (Choose three.)', odpoved: 'group-owner-all users' },
  { otazka: 'A user downloads a widget onto his Android phone but is puzzled to see that when the widget is touched an app is launched. What is a possible cause?', odpoved: 'The widget is associated with the app and this is the normal behavior.' },
  { otazka: 'What is the purpose of running mobile device apps in a sandbox?', odpoved: 'to prevent malicious programs from infecting the device' },
  { otazka: 'Refer to the exhibit. What is true of this mobile device screen?', odpoved: 'Text messages news photos and other content can be displayed in the different tiles.' },
  { otazka: 'Which built-in tool is available on a Mac OS X machine to perform disk backups?', odpoved: 'Time Machine' },
  { otazka: 'A user calls the help desk reporting that a laptop with Linux freezes on startup and displays kernel panic. What could cause this problem?', odpoved: 'A driver has become corrupted.' },
  { otazka: 'A user calls the help desk to report that a mobile device exhibits very slow performance. What could cause this problem?', odpoved: 'A power-intensive app is running in the background.' },
  { otazka: 'Which term describes a partition that is used to store and boot an operating system by default?', odpoved: 'active partition' },
  { otazka: 'Which term describes a file system that supports a partition size up to 16 exabytes?', odpoved: 'NTFS' },
  { otazka: 'Which term describes a file system for USB flash drives that supports files larger than 4 GB?', odpoved: 'exFAT' },
  { otazka: 'Which term describes a partition that supports up to 23 logical drives?', odpoved: 'extended partition' },
  { otazka: 'Which term describes a file system for optical disk media?', odpoved: 'CDFS' },
  { otazka: 'Which term describes a type of partition that would only exist on a hard disk that has an MBR?', odpoved: 'logical drive' },
  { otazka: 'Which term describes a type of storage device that supports a partition to be extended into adjacent unallocated space as long as it is contiguous?', odpoved: 'basic disk' },
  { otazka: 'Which term describes a general name for physical areas on a hard drive?', odpoved: 'partition' },
  { otazka: 'Which term describes a partition scheme that takes a portion of disk space of 512 bytes long and that contains the boot loader?', odpoved: 'MBR' },
  { otazka: 'Which term describes a type of storage device that supports a volume that can span across more than one disk?', odpoved: 'dynamic disk' },
  { otazka: 'A technician is booting a laptop that has Windows 10 installed with 2 GB RAM. The boot process is currently working on the following step: NTOSKRNL.EXE starts the login file called WINLOGON.EXE. What is the next step that will happen in the boot process?', odpoved: 'WINLOGON.EXE displays the Windows Welcome screen.' },
  { otazka: 'A user is booting a tablet that has Windows 10 installed. The boot process is currently working on the following step: WINLOGON.EXE displays the Windows Welcome screen What is the next step that will happen in the boot process?', odpoved: 'There are no more steps the boot process is complete.' },
  { otazka: 'A manager is booting a tablet that has Windows 8 installed. The boot process is currently working on the following step: POST. What is the next step that will happen in the boot process?', odpoved: 'BIOS locates and reads the configuration settings that are stored in the CMOS memory.' },
  { otazka: 'An accountant is booting a PC that has Windows 8 installed. The boot process is currently working on the following step: BIOS locates and reads the configuration settings that are stored in the CMOS memory. What is the next step that will happen in the boot process?', odpoved: 'The BIOS boots the computer using the first drive that contains a valid boot sector.' },
  { otazka: 'A network analyst is booting a PC that has Windows 7 installed with 2 GB RAM. The boot process is currently working on the following step: The code in the boot sector is executed and the control of the boot process is given to Windows Boot Manager. What is the next step that will happen in the boot process?', odpoved: 'Winload uses the path specified in BOOTMGR to find the boot partition.' },
  { otazka: 'An analyst is booting a desktop that has Windows 7 installed with 4 GB RAM. The boot process is currently working on the following step: Winload uses the path specified in BOOTMGR to find the boot partition. What is the next step that will happen in the boot process?', odpoved: 'WinLoad loads two files that make up the core of Windows: NTOSKRNL.EXE and HAL.DLL.' },
  { otazka: 'A gamer is booting a desktop that has Windows 7 installed on dynamic drives. The boot process is currently working on the following step: WinLoad reads the registry files chooses a hardware profile and loads the device drivers. What is the next step that will happen in the boot process?', odpoved: 'The Windows kernel takes over the boot process.' },
  { otazka: 'A technician is booting a laptop that has Windows 10 installed with 2 GB RAM. The boot process is currently working on the following step: The Windows kernel takes over the boot process. What is the next step that will happen in the boot process?', odpoved: 'NTOSKRNL.EXE starts the login file called WINLOGON.EXE.' },
  { otazka: 'A user is booting a laptop that has Windows 10 installed. The boot process is currently working on the following step: WINLOGON.EXE displays the Windows Welcome screen What is the next step that will happen in the boot process?', odpoved: 'There are no more steps the boot process is complete.' },
  { otazka: 'A manager is booting a tablet that has Windows 8 installed. The boot process is currently working on the following step: The Windows kernel takes over the boot process. What is the next step that will happen in the boot process?', odpoved: 'NTOSKRNL.EXE starts the login file called WINLOGON.EXE.' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the attacker was using a specific technique that affected the TCP three-way handshake. What is the type of network attack?', odpoved: 'SYN flood' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the attacker is using a technique that compares hashed passwords to potential hashes the hacker has. What is the type of network attack?', odpoved: 'rainbow table' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the DNS server was sent with an enormous amount of false requests thus overwhelming the server. What is the type of network attack?', odpoved: 'DoS' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the attacker is using a vulnerability that is known to the software vendor but not patched yet. What is the type of network attack?', odpoved: 'zero-day' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that zombies were used to attack the firewall. What is the type of network attack?', odpoved: 'DDoS' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that zombies were used to attack the firewall. What is the type of network attack?', odpoved: 'DDoS' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the attacker is using a table of words that potentially could be used as passwords. What is the type of network attack?', odpoved: 'dictionary' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the attacker injected false records on the server that translates IP addresses to domain names. What is the type of network attack?', odpoved: 'DNS poisoning' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the attacker is using a technique that compares hashed passwords to potential hashes the hacker has. What is the type of network attack?', odpoved: 'rainbow table' },
  { otazka: 'Users in a company have complained about network performance. After investigation the IT staff has determined that the attacker was using a specific technique that affected the TCP three-way handshake. What is the type of network attack?', odpoved: 'SYN flood' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for a company that wants a device to monitor incoming and outgoing traffic and stop any malicious activity. Which security technique should the technician recommend?', odpoved: 'Buy an IPS.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for a machine where the antimalware software cannot remove all of the malware. Which security technique should the technician recommend?', odpoved: 'Use Windows Safe Mode.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for a machine where the antimalware software cannot remove all of the malware. Which security technique should the technician recommend?', odpoved: 'Use Windows Safe Mode.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for preventing tailgating. Which security technique should the technician recommend?', odpoved: 'Use a mantrap.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for drive redundancy. Which security technique should the technician recommend?', odpoved: 'Implement a RAID.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for drive redundancy. Which security technique should the technician recommend?', odpoved: 'Implement a RAID.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for phishing. Which security technique should the technician recommend?', odpoved: 'Provide security awareness training.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for protecting a computer used to log in at a dental clinic from someone using a bootable disk containing hacking tools. Which security technique should the technician recommend?', odpoved: 'Disable ports.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for protecting a computer used to log in at a dental clinic from someone using a bootable disk containing hacking tools. Which security technique should the technician recommend?', odpoved: 'Disable ports.' },
  { otazka: 'A PC technician has been asked by a supervisor to recommend a security solution for a manager traveling who needs access to internal corporate resources. Which security technique should the technician recommend?', odpoved: 'Use a VPN.' },
  { otazka: 'Why would a gamer need to use the move command?', odpoved: 'to relocate a file from one Windows directory to another one' },
  { otazka: 'Why would a gamer need to use the copy command?', odpoved: 'to move that file to a different Windows directory while also leaving the file in the current location' },
  { otazka: 'Why would a university student need to use the robocopy command?', odpoved: 'to copy a group of files from one Windows directory to another' },
  { otazka: 'Why would a university student need to use the xcopy command?', odpoved: 'to copy files directories and subdirectories from one location to another' },
  { otazka: 'Why would a technical support representative need to use the format command?', odpoved: 'to prepare a hard drive to accept Windows files' },
  { otazka: 'Why would a technical support representative need to use the bootrec command?', odpoved: 'to help to repair the MBR that is suspected of having issues' },
  { otazka: 'Why would a technical support representative need to use the ipconfig command?', odpoved: 'to display the IPv6 address of the PC' },
  { otazka: 'Why would a user need to use the netstat command?', odpoved: 'to verify activity on the PC by displaying all active TCP connections on the device' },
  { otazka: 'Why would a user need to use the nslookup command?', odpoved: 'to query the Domain Name Sysytem (DNS) to get domain names and mapping information' },
  { otazka: 'Why would a manager need to use the ping command?', odpoved: 'to quickly verify connectivity by sending echo-request messages to the destination and receiving a series of echo-reply messages from that destination' },
  { otazka: 'Step One:', odpoved: 'The Windows boot loader Winload.exe loads.' },
  { otazka: 'Step Two:', odpoved: 'Ntoskrnl.exe and hal.dll are loaded.' },
  { otazka: 'Step Three:', odpoved: 'Winload.exe reads the Registry chooses a hardware profile and loads the device drivers.' },
  { otazka: 'Step Four:', odpoved: 'Ntoskrnl.exe takes over the process.' },
  { otazka: 'Step Five:', odpoved: 'Winlogon.exe is loaded and executes the logon process.' },
  { otazka: 'MTC This is a cross-platform standard specification for multimedia graphics.', odpoved: 'Open Graphics Library (OpenGL)' },
  { otazka: 'MTC This is a collection of APIs related to multimedia tasks for Microsoft Windows.', odpoved: 'DirectX' },
  { otazka: 'MTC This allows applications from older versions of Windows to operate on newer versions.', odpoved: 'Windows APIs' },
  { otazka: 'MTC This is a collection of APIs related to the development of Java programming', odpoved: ' Java APIs' },
  { otazka: 'MTT Allows for a process to have its affinity set.', odpoved: 'Details' },
  { otazka: 'MTT Displays resource utilization information for CPU memory network disk and others', odpoved: 'Performance' },
  { otazka: 'MTT Allows programs that are running on system startup to be disabled.', odpoved: 'Startup' },
  { otazka: 'MTT Allows for a start stop or restart of a particular service.', odpoved: 'Services' },
  { otazka: 'MTD a volume that is functioning properly', odpoved: ' Healthy' },
  { otazka: 'MTD a basic disk that is being converted into a dynamic disk', odpoved: 'Initializing' },
  { otazka: 'MTD a disk that does not contain a valid signature', odpoved: 'Not Initialized' },
  { otazka: 'MTD a basic dynamic disk that is accessible and shows no problems', odpoved: 'Online' },
  { otazka: 'MTD a dynamic disk that is corrupted or unavailable', odpoved: 'Offline' },
  { otazka: 'MTW The Advanced Encryption Standard (AES) cipher and preshared keys (PSKS) are used to encrypt communications.', odpoved: 'WPA2-Personal' },
  { otazka: 'MTW Authentication is passed from the access point to a centralized authentication RADIUS server.', odpoved: 'WPA2-Enterprise' },
  { otazka: 'MTW Data is sent unencrypted with no authentication.', odpoved: ' Open' },
  { otazka: 'MTI Scripting languages', odpoved: ' VBScript-Python-JavaScript' },
  { otazka: 'MTI Compiled languages', odpoved: ' C++-C#-Java' },
  
]